- name: install mysql component
  hosts: mysql
  become: yes
  tasks:
  - name: disable MySQL 8 version, and install MySQL 5.7
    ansible.builtin.command: yum module disable mysql -y 
  - name: Setup the MySQL5.7 repo file
    ansible.builtin.copy: 
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo
  - name: install mysql
    ansible.builtin.yum:
      name: mysql-community-server
      state: installed
  - name: start and enable mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: true
  - name: setup mysql root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
